In [ ]:
import pandas as pd #making some of our usual imports inorder to solve the problem in hand 
import tensorflow as tf
from tensorflow.keras.preprocessing import image

from tensorflow.keras.models import Sequential #importing our deep learing libraries
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Activation
from tensorflow.keras.preprocessing import image_dataset_from_directory

In [ ]:
IMG_SIZE = (256, 256)
train_dataset = image_dataset_from_directory('/content/drive/MyDrive/IRIS-Gender/labeled_data/Left/CLAHE/train', labels='inferred', label_mode='binary', class_names=None, 
                                             color_mode='rgb', batch_size=32, image_size= IMG_SIZE, shuffle=True)
validation_dataset = image_dataset_from_directory('/content/drive/MyDrive/IRIS-Gender/labeled_data/Left/CLAHE/valid', labels='inferred', label_mode='binary', class_names=None,
                                                  color_mode='rgb', batch_size=32, image_size=IMG_SIZE, shuffle=True)
test_dataset = image_dataset_from_directory('/content/drive/MyDrive/IRIS-Gender/labeled_data/Left/CLAHE/test', labels='inferred', label_mode='binary', class_names=None, 
                                            color_mode='rgb', batch_size=32, image_size=IMG_SIZE, shuffle=True)

Found 1292 files belonging to 2 classes.
Found 282 files belonging to 2 classes.
Found 281 files belonging to 2 classes.


In [ ]:
model = Sequential() #making our CNN
model.add(Conv2D(filters = 8, kernel_size = (9, 9), activation = 'relu', input_shape = (256,256,3)))
model.add(MaxPooling2D(pool_size = (2, 2)))
# model.add(Dropout(rate = 0.3))

model.add(Conv2D(filters = 16, kernel_size = (3, 3), activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))
# model.add(Dropout(rate = 0.2))

model.add(Conv2D(filters = 32, kernel_size = (3, 3), activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))
# model.add(Dropout(rate = 0.15))

model.add(Conv2D(filters = 64, kernel_size = (3, 3), activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Flatten())
# model.add(Dropout(rate = 0.15))
model.add(Dense(units = 512, activation = 'relu'))
model.add(Dense(units = 64, activation = 'relu'))
# model.add(Dropout(rate = 0.1))

model.add(Dense(units = 2, activation = 'softmax'))

In [ ]:
# model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# Compile model
import tensorflow as tf
base_learning_rate = 0.0001
model.compile(optimizer=tf.keras.optimizers.Adam(lr=base_learning_rate),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=False, reduction="auto", name="sparse_categorical_crossentropy"),
              metrics=['accuracy'])

In [ ]:
history = model.fit(train_dataset, epochs=5, validation_data=validation_dataset)

Epoch 1/5
41/41 [==============================] - 1101s 27s/step - loss: 6.2730 - accuracy: 0.6300 - val_loss: 0.6007 - val_accuracy: 0.7376
Epoch 2/5
41/41 [==============================] - 111s 3s/step - loss: 0.2486 - accuracy: 0.9110 - val_loss: 0.4034 - val_accuracy: 0.8546
Epoch 3/5
41/41 [==============================] - 111s 3s/step - loss: 0.1056 - accuracy: 0.9628 - val_loss: 0.4153 - val_accuracy: 0.8652
Epoch 4/5
41/41 [==============================] - 110s 3s/step - loss: 0.0571 - accuracy: 0.9845 - val_loss: 0.3838 - val_accuracy: 0.8794
Epoch 5/5
41/41 [==============================] - 110s 3s/step - loss: 0.0663 - accuracy: 0.9791 - val_loss: 0.4045 - val_accuracy: 0.8582


In [ ]:
def testing_image(image_directory): #testing out our model
    test_image = image.load_img(image_directory, target_size = (256, 256))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = model.predict(x = test_image)
    print(result)
    if result[0][0]>result[0][1]:
        prediction = 'female'
        # print(prediction)
        return 1
    else:
        prediction = 'male'
        # print(prediction)
        return 0

In [ ]:
import os
from tensorflow.keras.preprocessing import image
import numpy as np
test_dir='/content/drive/MyDrive/IRIS-Gender/labeled_data/Left/CLAHE/test'
test_male=os.listdir("/content/drive/MyDrive/IRIS-Gender/labeled_data/Left/CLAHE/test/male")
test_female=os.listdir("/content/drive/MyDrive/IRIS-Gender/labeled_data/Left/CLAHE/test/female")

In [ ]:
TP=0
FP=0
for file in test_male:
    x=testing_image(test_dir + '/male/' + str(file))
    if x==0 :
        TP+=1
    else:
        FP+=1

print(TP,FP)

[[0.36339644 0.6366036 ]]
[[0.22021914 0.77978086]]
[[0.07583734 0.9241627 ]]
[[8.513741e-04 9.991486e-01]]
[[2.3725402e-04 9.9976271e-01]]
[[5.753793e-04 9.994247e-01]]
[[3.628032e-04 9.996371e-01]]
[[0.00365333 0.99634665]]
[[0.00732877 0.99267125]]
[[4.7808862e-05 9.9995220e-01]]
[[6.9736845e-05 9.9993026e-01]]
[[3.184082e-05 9.999682e-01]]
[[0.01000742 0.98999256]]
[[0.00494235 0.9950577 ]]
[[0.00571025 0.99428976]]
[[0.12327623 0.87672377]]
[[0.1345903 0.8654097]]
[[0.03411478 0.9658852 ]]
[[0.34485334 0.65514666]]
[[0.10308789 0.8969121 ]]
[[0.2652225 0.7347775]]
[[7.2122697e-04 9.9927884e-01]]
[[0.01824694 0.9817531 ]]
[[0.0064631 0.9935369]]
[[5.7557120e-04 9.9942446e-01]]
[[0.00121915 0.9987809 ]]
[[0.00431083 0.9956892 ]]
[[1.8435762e-04 9.9981564e-01]]
[[3.139009e-04 9.996861e-01]]
[[1.9647507e-04 9.9980360e-01]]
[[0.00176987 0.99823016]]
[[0.01121981 0.98878014]]
[[0.02222507 0.977775  ]]
[[0.01995268 0.9800473 ]]
[[0.01224546 0.9877545 ]]
[[0.01936273 0.9806373 ]]
[[0.0394

In [ ]:
TN=0
FN=0
for file in test_female:
    x=testing_image(test_dir + '/female/' + str(file))
    if x==1 :
        TN+=1
    else:
        FN+=1

print(TN,FN)

[[9.999937e-01 6.325285e-06]]
[[9.999956e-01 4.466227e-06]]
[[9.9999416e-01 5.7993529e-06]]
[[0.01428216 0.9857179 ]]
[[0.17893454 0.8210654 ]]
[[0.03339071 0.96660936]]
[[0.9523146  0.04768535]]
[[0.8056459  0.19435415]]
[[0.98510635 0.01489365]]
[[9.9999237e-01 7.6356355e-06]]
[[9.9997222e-01 2.7763508e-05]]
[[9.9994028e-01 5.9707614e-05]]
[[0.00389733 0.9961027 ]]
[[0.01109588 0.9889042 ]]
[[0.01748235 0.98251766]]
[[9.9997020e-01 2.9782797e-05]]
[[9.9999487e-01 5.1172506e-06]]
[[9.9999905e-01 9.2933828e-07]]
[[9.9991083e-01 8.9208523e-05]]
[[9.999455e-01 5.445835e-05]]
[[9.999263e-01 7.364588e-05]]
[[9.9980527e-01 1.9471304e-04]]
[[9.995907e-01 4.092804e-04]]
[[9.9989581e-01 1.0413375e-04]]
[[0.9960974  0.00390263]]
[[9.9948251e-01 5.1742286e-04]]
[[9.9920136e-01 7.9865422e-04]]
[[9.993186e-01 6.814038e-04]]
[[0.9986945 0.0013056]]
[[0.9532901  0.04670983]]
[[9.9982578e-01 1.7428324e-04]]
[[9.9993503e-01 6.4988439e-05]]
[[9.9999249e-01 7.5360063e-06]]
[[0.9891473  0.01085273]]
[[9.

In [ ]:
test_Accuracy=(TP+TN)/(TP+TN+FP+FN)
print(test_Accuracy)

0.9323843416370107


In [ ]:
!pip install PyYAML
# serialize model to YAML
model_yaml = model.to_yaml()
with open("model.yaml", "w") as yaml_file:
    yaml_file.write(model_yaml)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk


In [ ]:
# load YAML and create model
yaml_file = open('model.yaml', 'r')
loaded_model_yaml = yaml_file.read()
yaml_file.close()

In [ ]:
from keras.models import model_from_yaml
loaded_model = model_from_yaml(loaded_model_yaml)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")

Loaded model from disk


In [ ]:
base_learning_rate = 0.0001
loaded_model.compile(optimizer=tf.keras.optimizers.Adam(lr=base_learning_rate),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=False, reduction="auto", name="sparse_categorical_crossentropy"),
              metrics=['accuracy'])

In [ ]:
def testing_image_afterLoading(image_directory): #testing out our model
    test_image = image.load_img(image_directory, target_size = (256, 256))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = loaded_model.predict(x = test_image)
    print(result)
    if result[0][0]> result[0][1]:
        prediction = 'female'
        print(prediction)
        return 1
    else:
        prediction = 'male'
        print(prediction)
        return 0

In [ ]:
print(testing_image_afterLoading("/content/1602.JPG"))

[[0.99105024 0.00894979]]
female
1


In [ ]:
print(testing_image_afterLoading("/content/1609.JPG"))

[[0.9739657  0.02603423]]
female
1


In [ ]:
print(testing_image_afterLoading("/content/drive/MyDrive/IRIS-Gender/labeled_data/Left/CLAHE/Male/673/2673.JPG"))

In [52]:
print(testing_image_afterLoading("/content/2609.JPG"))

[[0.9702378  0.02976219]]
female
1


In [48]:
import numpy as np
import cv2 as cv
img = cv.imread('/content/2609.JPG',0)
# create a CLAHE object (Arguments are optional).
clahe = cv.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
cl1 = clahe.apply(img)

cv2.imwrite('/content/2609.JPG', cl1) 


True

In [53]:
print(testing_image_afterLoading("/content/2609_clahy.JPG"))

[[0.07583734 0.9241627 ]]
male
0
